export interface ProdutosInput{
    id              :number,
    nome            :string,
    descricao       :string,
    id_categoria    :number,
    valor           :number,
    perc_desc       :number,
    avaliacao       :number,
    estoque         :number,
    id_marca        :number,
    sku             :string,
    peso            :number,
    largura         :number,
    altura          :number,
    profundidade    :number,
    garantia        :string,
    envio           :string,
    disponibilidade :string,
    pol_devolucao   :string,
    qtd_min         :number,
    dt_criacao      :Date,
    dt_atualizado   :Date,
    barcode         :string,
    qr_code         :string,
    thumbnail       :string
}